define(function (require, exports, module) {
    var inDebug = false;

    var map = {
        add: 20,
        addLayer: 118,
        addPoint: 160,
        addView: 146,
        blur: 163,
        canGoBackOrForward: 126,
        cancel: 121,
        captureAudio: 99,
        captureImage: 100,
        captureVideo: 101,
        closeSlider: 173,
        create: 3,
        destroy: 4,
        destroyAll: 5,
        directShare: 117,
        dismiss: 184,
        dismissMenu: 127,
        dopay: 107,
        exit: 1,
        focus: 164,
        followSite: 108,
        get: 102,
        getClientHeight: 30,
        getClientLeft: 31,
        getClientTop: 32,
        getClientWidth: 33,
        getLocationCityName: 12,
        getMethodMapping: 6,
        getNativeLayerSize: 13,
        getPicture: 98,
        getSubscribedAppinfos: 109,
        getUniqueId: 110,
        goBackOrForward: 128,
        goBack: 1128,
        handleLoading: 148,
        hideInputMethod: 14,
        hideLoading: 149,
        hideToolbar: 175,
        isBind: 111,
        isLogin: 89,
        jsHandleBack: 2,
        loadUrl: 129,
        login: 90,
        postMessage: 119,
        querySubscribe: 15,
        registerMulticast: 112,
        registerUnicast: 113,
        reload: 130,
        remove: 21,
        removeLayer: 120,
        removeViewAt: 147,
        scrollBy: 170,
        scrollTo: 171,
        seekToAudio: 91,
        setAlignItems: 151,
        setAlignSelf: 34,
        setAlpha: 35,
        setBackgroundColor: 36,
        setBorderBottomColor: 37,
        setBorderBottomLeftRadius: 38,
        setBorderBottomRightRadius: 39,
        setBorderBottomWidth: 40,
        setBorderColor: 41,
        setBorderLeftColor: 42,
        setBorderLeftWidth: 43,
        setBorderRadius: 44,
        setBorderRightColor: 45,
        setBorderRightWidth: 46,
        setBorderTopColor: 47,
        setBorderTopLeftRadius: 48,
        setBorderTopRightRadius: 49,
        setBorderTopWidth: 50,
        setBorderWidth: 51,
        setBottom: 52,
        setCancelable: 185,
        setCanceledOnTouchOutside: 186,
        setColor: 133,
        setCurrentItem: 178,
        setData: 176,
        setDefaultSource: 123,
        setDragBounds: 161,
        setDragMode: 162,
        setDuration: 8,
        setEasing: 9,
        setEditable: 165,
        setEllipsize: 134,
        setFlex: 53,
        setFlexDirection: 152,
        setFlexWrap: 153,
        setFont: 135,
        setFontFamily: 136,
        setFontSize: 137,
        setFontStyle: 138,
        setFontWeight: 139,
        setFrom: 22,
        setFromColor: 23,
        setGravityHorizontal: 181,
        setGravityVertical: 182,
        setHeight: 54,
        setJustifyContent: 154,
        setKeyboardType: 166,
        setLeft: 55,
        setLineHeight: 140,
        setLinkage: 172,
        setLoop: 179,
        setLoopScrollDuration: 180,
        setMargin: 56,
        setMarginBottom: 57,
        setMarginLeft: 58,
        setMarginRight: 59,
        setMarginTop: 60,
        setMaxHeight: 61,
        setMaxLines: 141,
        setMaxSlideWidth: 174,
        setMaxWidth: 62,
        setMinHeight: 63,
        setMinWidth: 64,
        setMultiline: 142,
        setNumberOfLines: 143,
        setPadding: 155,
        setPaddingBottom: 156,
        setPaddingLeft: 157,
        setPaddingRight: 158,
        setPaddingTop: 159,
        setPassword: 167,
        setPlaceholder: 168,
        setPlaceholderTextColor: 169,
        setPosition: 65,
        setProp: 24,
        setRepeatCount: 122,
        setResizeMode: 124,
        setRight: 66,
        setScaleX: 67,
        setScaleY: 68,
        setSelectorBackgroundColor: 69,
        setSelectorBorderBottomColor: 70,
        setSelectorBorderBottomLeftRadius: 71,
        setSelectorBorderBottomRightRadius: 72,
        setSelectorBorderBottomWidth: 73,
        setSelectorBorderColor: 74,
        setSelectorBorderLeftColor: 75,
        setSelectorBorderLeftWidth: 76,
        setSelectorBorderRadius: 77,
        setSelectorBorderRightColor: 78,
        setSelectorBorderRightWidth: 79,
        setSelectorBorderTopColor: 80,
        setSelectorBorderTopLeftRadius: 81,
        setSelectorBorderTopRightRadius: 82,
        setSelectorBorderTopWidth: 83,
        setSelectorBorderWidth: 84,
        setSource: 125,
        setStartOffset: 10,
        setTarget: 11,
        setTextAlign: 144,
        setTo: 25,
        setToColor: 26,
        setTop: 85,
        setTranslationX: 86,
        setTranslationY: 87,
        setType: 27,
        setUpdateColor: 28,
        setUrl: 29,
        setValue: 145,
        setVolume: 92,
        setWidth: 88,
        shareApp: 16,
        show: 183,
        showInputMethod: 17,
        showLoading: 150,
        showMenu: 131,
        showToolbar: 177,
        speedFF: 93,
        start: 103,
        startListen: 105,
        startPlayingAudio: 94,
        startRecordingAudio: 95,
        stop: 104,
        stopListen: 106,
        stopPlayingAudio: 96,
        stopRecordingAudio: 97,
        subscribe: 18,
        unSubscribeLight: 114,
        unregisterMulticast: 115,
        unregisterUnicast: 116,
        unsubscribe: 19,
        update: 7,
        updateMenu: 132,

        canGoBack: 2000, //ios only, in current
        canGoForward: 2001 //ios only, in current
    };

    if (inDebug) {
        console.warn("in debug, use string");
        map = {};
    }

    exports.tryGetMethodId = function (methodName) {
        return map[methodName] || methodName;
    };
    exports.setMap = function (newMap) {
        map = newMap;
    };
});
